### PR TITLE
Modify ```equipItem``` to accept ```LivingEntity```

### PR DESCRIPTION
**Pull request by powerboat9**

### CODE REVIEW

**Review by emilyploszaj — CHANGES_REQUESTED** [review]
This is a breaking API changes that would crash countless mods.

**Comment by powerboat9** [comment]
Sorry, created a new method ```equipItemLiving``` instead

**Comment by emilyploszaj** [comment]
Is it possible to have them be named the same?

**Comment by powerboat9** [comment]
I wasn't sure, but it looks like [yes](https://docs.oracle.com/javase/specs/jls/se9/html/jls-8.html#jls-8.4.9)

**Review by emilyploszaj — APPROVED** [review]

**Pull request merged**
