### PR TITLE
Update for 1.19

### PR DESCRIPTION
**Pull request by florensie**
I'm getting a head start on updating to 1.19 for one of my mods and needed this. I intend to keep this updated, to be undrafted when 1.19 has a stable (pre)release.

### CODE REVIEW

**Review by emilyploszaj — COMMENTED** [review]
In general looks good. Is 1.19 around the corner or something? Or is this just to give something to developers? Typically I don't update trinkets until pre releases. Also what's up with the translatable text thing?

**Comment by florensie** [comment]
Here's a Github gist explaining the refactors Mojang made to the Text classes: https://gist.github.com/apple502j/f2783990bac68a35acef2f7e4c901a2a

**Comment by RealRTTV** [comment]
Now that we're on rc2 do you think this could be tested and merged, or is it outdated now since there have been _ changes from 22w16b-rc2?

**Comment by florensie** [comment]
Was pretty much good to go from last changes, just a small merge conflict and some dependency updates.

**Comment by emilyploszaj** [comment]
Finally had a look over, looks good, I'm gonna merge, update to 1.19 proper, and make a release.

**Pull request merged**
