### PR TITLE
Ported to 1.19.3

### PR DESCRIPTION
**Pull request by Ayutac**
…yet. Maybe I will add it in, maybe someone else will.

CardinalComponents was just updated (by me), so hence I'm looking at this now.

### CODE REVIEW

**Comment by Ayutac** [comment]
The only thing that is left is the creative menu mixin

**Comment by Ayutac** [comment]
Port finished now, needs testing though (because I am not familiar with testing this mod)

**Comment by emilyploszaj** [comment]
Thanks for the contribution, I'll take a look at it when I get the chance and hopefully get this released soon

**Review by emilyploszaj — APPROVED** [review]

**Comment by Ayutac** [comment]
any idea when the new version will be accessible via dependencies? I'm looking at https://maven.terraformersmc.com/releases/dev/emi/trinkets

**Pull request merged**
